const mockCarData = [
  {
    "CarID": 7,
    "MakeID": 77,
    "ModelID": 239,
    "Gearbox": "Automatic",
    "FuelType": "Gasoline",
    "Description": "",
    "FactoryYear": 2022,
    "KilometersCount": 10000,
    "NumberOwners": 2,
    "LicensePlate": "30E-32432",
    "RegistrationStatus": "remaining",
    "MadeIn": "Japan",
    "EngineCapacity": "2",
    "SeatNumber": 5,
    "DoorNumber": 4,
    "Weight": "1",
    "InstallmentLengthMin": 1,
    "InstallmentLengthMax": 8,
    "InterestRateMin": 1,
    "InterestRateMax": 100,
    "MonthlyInstallmentMin": 1,
    "MonthlyInstallmentMax": 100,
    "Title": "2019 Honda Civic Sport",
    "Status": "selling",
    "Condition": "USED",
    "Price": "15000",
    "SellerID": null,
    "BuyerID": null,
    "CreatedAt": "2024-12-05T10:18:17.000Z",
    "SoldAt": null,
    "images": [
      "https://res.cloudinary.com/dhgwdfhcf/image/upload/v1733393895/cars/xboegvybj89qzdrc7wvw.png",
      "https://res.cloudinary.com/dhgwdfhcf/image/upload/v1733393896/cars/rmcqhkhmsfwsh0c6xjkg.webp"
    ],
    "carmakes": {
      "MakeID": 77,
      "Name": "Toyota"
    },
    "carmodels": {
      "ModelID": 239,
      "MakeID": 77,
      "Name": "Camry"
    },
    "users_cars_SellerIDTousers": null
  },
  {
    "CarID": 6,
    "MakeID": 16,
    "ModelID": 53,
    "Gearbox": "Automatic",
    "FuelType": "Gasoline/Petrol",
    "Description": "image",
    "FactoryYear": 2024,
    "KilometersCount": 1,
    "NumberOwners": 1,
    "LicensePlate": "1",
    "RegistrationStatus": "remaining",
    "MadeIn": "Vietnam",
    "EngineCapacity": "1",
    "SeatNumber": 2,
    "DoorNumber": 2,
    "Weight": "1",
    "InstallmentLengthMin": 1,
    "InstallmentLengthMax": 8,
    "InterestRateMin": 1,
    "InterestRateMax": 100,
    "MonthlyInstallmentMin": 1,
    "MonthlyInstallmentMax": 100,
    "Title": "Test Image",
    "Status": "selling",
    "Condition": "NEW",
    "Price": "1111111111",
    "SellerID": null,
    "BuyerID": null,
    "CreatedAt": "2024-12-05T07:43:14.000Z",
    "SoldAt": null,
    "images": [],
    "carmakes": {
      "MakeID": 16,
      "Name": "Citroen"
    },
    "carmodels": {
      "ModelID": 53,
      "MakeID": 16,
      "Name": "C3"
    },
    "users_cars_SellerIDTousers": null
  },
  {
    "CarID": 5,
    "MakeID": 7,
    "ModelID": 21,
    "Gearbox": "Semi-automatic",
    "FuelType": "Electric",
    "Description": "Kien's car",
    "FactoryYear": 2024,
    "KilometersCount": 420,
    "NumberOwners": 420,
    "LicensePlate": "29P1-42069",
    "RegistrationStatus": "remaining",
    "MadeIn": "Vietnam",
    "EngineCapacity": "4.2",
    "SeatNumber": 4,
    "DoorNumber": 4,
    "Weight": "420",
    "InstallmentLengthMin": 2,
    "InstallmentLengthMax": 4,
    "InterestRateMin": 1,
    "InterestRateMax": 42,
    "MonthlyInstallmentMin": 1,
    "MonthlyInstallmentMax": 42,
    "Title": "Kien's Car",
    "Status": "selling",
    "Condition": "NEW",
    "Price": "420420420",
    "SellerID": null,
    "BuyerID": null,
    "CreatedAt": "2024-12-05T07:39:10.000Z",
    "SoldAt": null,
    "images": [],
    "carmakes": {
      "MakeID": 7,
      "Name": "Bentley"
    },
    "carmodels": {
      "ModelID": 21,
      "MakeID": 7,
      "Name": "Bentayga"
    },
    "users_cars_SellerIDTousers": null
  },
  {
    "CarID": 4,
    "MakeID": 7,
    "ModelID": 21,
    "Gearbox": "Semi-automatic",
    "FuelType": "Electric",
    "Description": "Kien's car",
    "FactoryYear": 2024,
    "KilometersCount": 420,
    "NumberOwners": 420,
    "LicensePlate": "29P1-42069",
    "RegistrationStatus": "remaining",
    "MadeIn": "Vietnam",
    "EngineCapacity": "4.2",
    "SeatNumber": 4,
    "DoorNumber": 4,
    "Weight": "420",
    "InstallmentLengthMin": 2,
    "InstallmentLengthMax": 4,
    "InterestRateMin": 1,
    "InterestRateMax": 42,
    "MonthlyInstallmentMin": 1,
    "MonthlyInstallmentMax": 42,
    "Title": "Kien's Car",
    "Status": "selling",
    "Condition": "NEW",
    "Price": "420420420",
    "SellerID": null,
    "BuyerID": null,
    "CreatedAt": "2024-12-05T07:39:05.000Z",
    "SoldAt": null,
    "images": [
      "https://res.cloudinary.com/dhgwdfhcf/image/upload/v1733390222/cars/wzb74nrwfseum22rpfn0.jpg"
    ],
    "carmakes": {
      "MakeID": 7,
      "Name": "Bentley"
    },
    "carmodels": {
      "ModelID": 21,
      "MakeID": 7,
      "Name": "Bentayga"
    },
    "users_cars_SellerIDTousers": null
  },
  {
    "CarID": 3,
    "MakeID": 77,
    "ModelID": 239,
    "Gearbox": "Semi-automatic",
    "FuelType": "Hybrid engine",
    "Description": "Xe còn mới, chạy 2000 km\nCần ra đi nhanh",
    "FactoryYear": 1997,
    "KilometersCount": 4321415,
    "NumberOwners": 34,
    "LicensePlate": "30E-32432",
    "RegistrationStatus": "remaining",
    "MadeIn": "Thailand",
    "EngineCapacity": "2",
    "SeatNumber": 5,
    "DoorNumber": 4,
    "Weight": "1",
    "InstallmentLengthMin": 2,
    "InstallmentLengthMax": 4,
    "InterestRateMin": 20,
    "InterestRateMax": 70,
    "MonthlyInstallmentMin": 30,
    "MonthlyInstallmentMax": 60,
    "Title": "Kia Senota",
    "Status": "selling",
    "Condition": "NEW",
    "Price": "700000000",
    "SellerID": null,
    "BuyerID": null,
    "CreatedAt": "2024-12-05T05:03:04.000Z",
    "SoldAt": null,
    "images": [],
    "carmakes": {
      "MakeID": 77,
      "Name": "Toyota"
    },
    "carmodels": {
      "ModelID": 239,
      "MakeID": 77,
      "Name": "Camry"
    },
    "users_cars_SellerIDTousers": null
  },
  {
    "CarID": 2,
    "MakeID": 77,
    "ModelID": 239,
    "Gearbox": "Manual",
    "FuelType": "Gasoline/Petrol",
    "Description": "Xe còn mới, chạy 2000 km\nCần ra đi nhanh",
    "FactoryYear": 2022,
    "KilometersCount": 10000,
    "NumberOwners": 2,
    "LicensePlate": "30E-32432",
    "RegistrationStatus": "remaining",
    "MadeIn": "Japan",
    "EngineCapacity": "2",
    "SeatNumber": 5,
    "DoorNumber": 4,
    "Weight": "1",
    "InstallmentLengthMin": 2,
    "InstallmentLengthMax": 4,
    "InterestRateMin": 20,
    "InterestRateMax": 70,
    "MonthlyInstallmentMin": 30,
    "MonthlyInstallmentMax": 60,
    "Title": "Huyndai Tucson i300",
    "Status": "selling",
    "Condition": "USED",
    "Price": "700000000",
    "SellerID": null,
    "BuyerID": null,
    "CreatedAt": "2024-12-05T05:02:02.000Z",
    "SoldAt": null,
    "images": [],
    "carmakes": {
      "MakeID": 77,
      "Name": "Toyota"
    },
    "carmodels": {
      "ModelID": 239,
      "MakeID": 77,
      "Name": "Camry"
    },
    "users_cars_SellerIDTousers": null
  },
  {
    "CarID": 1,
    "MakeID": 77,
    "ModelID": 239,
    "Gearbox": "Automatic",
    "FuelType": "Gasoline/Petrol",
    "Description": "",
    "FactoryYear": 2022,
    "KilometersCount": 10000,
    "NumberOwners": 2,
    "LicensePlate": "30E-32432",
    "RegistrationStatus": "remaining",
    "MadeIn": "Japan",
    "EngineCapacity": "2",
    "SeatNumber": 5,
    "DoorNumber": 4,
    "Weight": "1",
    "InstallmentLengthMin": 2,
    "InstallmentLengthMax": 4,
    "InterestRateMin": 20,
    "InterestRateMax": 70,
    "MonthlyInstallmentMin": 10,
    "MonthlyInstallmentMax": 70,
    "Title": "Hyundai Grand i10 (Sang tên chính chủ)",
    "Status": "selling",
    "Condition": "USED",
    "Price": "15000",
    "SellerID": null,
    "BuyerID": null,
    "CreatedAt": "2024-12-05T04:59:58.000Z",
    "SoldAt": null,
    "images": [
      "https://res.cloudinary.com/dhgwdfhcf/image/upload/v1733392545/cars/dr4l4d7pvc7hhk9wp4kr.webp"
    ],
    "carmakes": {
      "MakeID": 77,
      "Name": "Toyota"
    },
    "carmodels": {
      "ModelID": 239,
      "MakeID": 77,
      "Name": "Camry"
    },
    "users_cars_SellerIDTousers": null
  }
]
export default mockCarData;
